version: "3.8"
services:
  propertymanagementdotnetwebapi:
    container_name: propertymanagementdotnetwebapi
    image: ${DOCKER_REGISTRY-}propertymanagementdotnetwebapi
    build: 
      context: propertymanagementdotnetwebapi
      dockerfile: Dockerfile      
    ports:
      - "5000:80"